name: Generate GitHub Contribution Snake
on:
  schedule:
    - cron: "0 0 * * *"
    - cron: "30 18 * * *"
  workflow_dispatch:
  push:

jobs:
  generate-snake:
    name: Generate Snake
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            contrib/github-snake.svg
            contrib/github-snake-dark.svg?palette=github-dark

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update Contribution Snake
          file_pattern: contrib/*
