name: WakaTime README

on:
  schedule:
    - cron: "0 0 * * *"
    - cron: "30 18 * * *"
  workflow_dispatch:
  push:

jobs:
  update-readme:
    name: Update README with Metrics
    runs-on: ubuntu-latest
    steps:
      - name: Update README
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LINES_OF_CODE: true
          COMMIT_MESSAGE: Update WakaTime Stats
